busalert/Bus/Controllers/AloneClientsController.cs
using Bus.Models;
using ClosedXML.Excel;
using DocumentFormat.OpenXml.Spreadsheet;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Data;
using System.Data.Entity;
using System.Net;
using System.Text;
using System.ComponentModel;

namespace Bus.Controllers
{
    [Authorize(Roles = "Admin")]
    [RequireHttps]
    public class AloneClientsController : Controller
    {

        private ApplicationDbContext db = new ApplicationDbContext();
        // GET: AloneClients
        public async Task<ActionResult> Index()
        {




            List<Client> clientsList = new List<Client>();
            foreach (var item in await db.Clients.GroupBy(p => p.Phone).ToListAsync())
            {
                clientsList.Add(item.First());
            }




            return View(clientsList);
        }

        public async Task<ActionResult> Mailing(string smstext)
        {
            List<SMSSend> SMSList = new List<SMSSend>();
            if (smstext != "" && smstext != null)
            {
                SMSWorker sms = new SMSWorker();
                var auth = sms.Auth("busforest", "5163809a");

                foreach (var item in await db.Clients.GroupBy(p => p.Phone).ToListAsync())
                {
                    var send = sms.SendSMS("Msg", item.First().Phone, smstext, null);
                    if (send[0] == "Сообщения успешно отправлены")
                    {
                        SMSList.Add(new SMSSend() { Verify = true, NumberUser = item.First().Phone, FIO = item.First().FIO });
                    }
                    else
                    {
                        SMSList.Add(new SMSSend() { Verify = false, NumberUser = item.First().Phone, FIO = item.First().FIO });
                    }
                }
            }
            return PartialView(SMSList);
        }



        public async Task<ActionResult> Excel()
        {
            GridView gv = new GridView();


            List<Client> clientsList = new List<Client>();
            foreach (var item in await db.Clients.GroupBy(p => p.Phone).ToListAsync())
            {
                clientsList.Add(item.First());
            }




            gv.DataSource = clientsList;
            gv.DataBind();
            Response.ClearContent();
            Response.Buffer = true;
            Response.AddHeader("content-disposition", "attachment; filename=Clients.xls");
            Response.ContentType = "application/ms-excel";
            Response.ContentEncoding = Encoding.UTF8;
            Response.Charset = "";
            StringWriter sw = new StringWriter();
            HtmlTextWriter htw = new HtmlTextWriter(sw);
            gv.RenderControl(htw);
            Response.Output.Write(sw.ToString());
            Response.Flush();
            Response.End();
            return RedirectToAction("Index");
        }


    }
}

busalert/Bus/Controllers/SMSController.cs
using Bus.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Bus.Controllers
{
    [RequireHttps]
    public class SMSController : Controller
    {

        private ApplicationDbContext db = new ApplicationDbContext();
        // GET: SMS
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult LastSMS()
        {
            SMSWorker sms = new SMSWorker();
            var auth = sms.Auth("busforest", "5163809a");

            return Content("Осталось СМС: " + sms.GetCreditBalance());
        }
      
            
        
    }
}

busalert/Bus/Views/AloneClients/Index.cshtml
@model IEnumerable<Bus.Models.Client>

@{
    ViewBag.Title = "Index";
}
<h1 align="center">Клиенты</h1>
<table class="table">
    <tr>
       
        <th>
            @Html.DisplayNameFor(model => model.FIO)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Phone)
        </th>
       
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            
            <td>
                @Html.DisplayFor(modelItem => item.FIO)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Phone)
            </td>
            
           
        </tr>
    }

</table>

<a href="@Url.Action("index","manage")"><button>Личный Кабинет</button></a>
<a href="@Url.Action("excel")"><button>Скачать Excel</button></a>
<div class="form-group">
    <div class="col-md-offset-2 col-md-10">
        <div id="remain">@{Html.RenderAction("LastSMS", "SMS");}</div>
    </div>
</div>

@using (Ajax.BeginForm("Mailing", "aloneclients", new AjaxOptions
{
    UpdateTargetId = "reportSMS",
    HttpMethod = "POST",
    InsertionMode = InsertionMode.Replace,


    OnComplete = "OnComplete",
    LoadingElementId = "LoadingDiv",
    Confirm = "Выполнить Рассылку Клиентам?"

}))
{


    <div class="form-horizontal">
        <h4>Разсылка Сообщений</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <label>Введдите текст сообщения для Разсылки</label>
            <div class="col-md-10">
                <textarea name="smsText"></textarea>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Отправить" class="btn btn-default" />
            </div>
        </div>
    </div>

    <div id="reportSMS"></div>
}

<script type="text/javascript" src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

busalert/Bus/Views/AloneClients/Mailing.cshtml
@model IEnumerable<Bus.Models.SMSSend>

@{
    ViewBag.Title = "Index";
}

<h2>Отчет об Рассылке</h2>
@if (Model.Count() != 0)
{
<table class="table">
    <tr>
        <th>
            ФИО
        </th>
        <th>
           Телефон
        </th>
        <th>
            Доставка
        </th>
       
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FIO)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NumberUser)
            </td>

            <td>
                @if (item.Verify == true)
                {
                    <label style="color:green;" >Успешно</label>
                }
                else
                {
                    <label style="color:red;">Не Успешно</label>
                }
            </td>
           
        </tr>
    }

</table>
}
else
{
    <h2>Не Передано Сообщение для Отправки</h2>
}