busalert/Bus/Controllers/ClientsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Bus.Models;
using Yandex.Geocoder;

namespace Bus.Controllers
{
    public class ClientsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Clients
        public async Task<ActionResult> Index()
        {
            var clients = db.Clients.Include(c => c.Route);
            return View(await clients.ToListAsync());
        }

        // GET: Clients/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Client client = await db.Clients.FindAsync(id);
            if (client == null)
            {
                return HttpNotFound();
            }
            return View(client);
        }

        // GET: Clients/Create
   /*     public ActionResult Create()
        {
            ViewBag.RouteId = new SelectList(db.Routes, "Id", "NameRoute");
            return View();
        }

        // POST: Clients/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,Date,FIO,Phone,PlaceBus,RoadType,CoordsFrom,CoordsTo,RouteId")] Client client)
        {
            if(await db.Clients.Where(p=> p.RoadType == client.RoadType && p.PlaceBus == client.PlaceBus && p.Date == client.Date && p.RouteId == client.RouteId).FirstOrDefaultAsync() != null)
            {
                ModelState.AddModelError("Дубликат", "Это Место В Автобусе Уже занято");
            }

            var geocoderFrom = new YandexGeocoder
            {
                SearchQuery = client.CoordsFrom,
                Results = 1,

                LanguageCode = LanguageCode.ru_RU


            };

            var coordFromFirst = geocoderFrom.GetResults();

            if (geocoderFrom.GetResults().Count == 0)
            {
                ModelState.AddModelError("Локация", "Адрес Отправки Не Определился");
            }
            else
            {
                client.CoordsFromR = geocoderFrom.GetResults().First().Point.Latitude + "," + geocoderFrom.GetResults().First().Point.Longitude;
            }

            var geocoderTo = new YandexGeocoder
            {
                SearchQuery = client.CoordsTo,
                Results = 1,

                LanguageCode = LanguageCode.ru_RU
            };

            if (geocoderTo.GetResults().Count == 0)
            {
                ModelState.AddModelError("Локация", "Адрес Прибытия Не Определился");
            }
            else
            {
                client.CoordsToR = geocoderTo.GetResults().First().Point.Latitude + "," + geocoderTo.GetResults().First().Point.Longitude;
            }


            if (ModelState.IsValid)
            {
                db.Clients.Add(client);
                await db.SaveChangesAsync();
                return RedirectToAction("Index", "Home");
            }

            ViewBag.RouteId = new SelectList(db.Routes, "Id", "NameRoute", client.RouteId);
            return View(client);
        }*/

        // GET: Clients/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Client client = await db.Clients.FindAsync(id);
            if (client == null)
            {
                return HttpNotFound();
            }


            ViewBag.RouteId = new SelectList(db.Routes.Where(p => p.DateRoute == client.Date && p.RoadTypeRoute == client.RoadType ), "Id", "NameRoute", client.RouteId);
            return View(client);
        }
        
        // POST: Clients/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Date,FIO,Phone,PlaceBus,RoadType,CoordsFrom,CoordsTo,RouteId")] Client client)
        {
         


            if (client.RouteId == 0)
            {
                client.RouteId = null;
            }

            var geocoderFrom = new YandexGeocoder
            {
                SearchQuery = client.CoordsFrom,
                Results = 1,

                LanguageCode = LanguageCode.ru_RU


            };

            var coordFromFirst = geocoderFrom.GetResults();

            if (geocoderFrom.GetResults().Count == 0)
            {
                ModelState.AddModelError("Локация", "Адрес Отправки Не Определился");
            }
            else
            {
                client.CoordsFromR = geocoderFrom.GetResults().First().Point.Latitude + "," + geocoderFrom.GetResults().First().Point.Longitude;
            }

            var geocoderTo = new YandexGeocoder
            {
                SearchQuery = client.CoordsTo,
                Results = 1,

                LanguageCode = LanguageCode.ru_RU
            };

            if (geocoderTo.GetResults().Count == 0)
            {
                ModelState.AddModelError("Локация", "Адрес Прибытия Не Определился");
            }
            else
            {
                client.CoordsToR = geocoderTo.GetResults().First().Point.Latitude + "," + geocoderTo.GetResults().First().Point.Longitude;
            }

            if (ModelState.IsValid)
            {
                db.Entry(client).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index", "Home");
            }
            ViewBag.RouteId = new SelectList(db.Routes.Where(p => p.DateRoute == client.Date && p.RoadTypeRoute == client.RoadType), "Id", "NameRoute", client.RouteId);
            return View(client);
        }

        // GET: Clients/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Client client = await db.Clients.FindAsync(id);
            if (client == null)
            {
                return HttpNotFound();
            }
            return View(client);
        }

        // POST: Clients/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Client client = await db.Clients.FindAsync(id);
            db.Clients.Remove(client);
            await db.SaveChangesAsync();
            return RedirectToAction("Index", "Home"); 
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

busalert/Bus/Controllers/RoutesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Bus.Models;

namespace Bus.Controllers
{
    public class RoutesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Routes
        public async Task<ActionResult> Index()
        {
            return View(await db.Routes.ToListAsync());
        }

        // GET: Routes/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Route route = await db.Routes.FindAsync(id);
            if (route == null)
            {
                return HttpNotFound();
            }
            return View(route);
        }

        // GET: Routes/Create
      /*  public ActionResult Create()
        {
            return View();
        }

        // POST: Routes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,NameDriver,NameRoute,RoadTypeRoute,DateRoute")] Route route)
        {

            if (await db.Routes.Where(p => p.RoadTypeRoute == route.RoadTypeRoute  && p.DateRoute == route.DateRoute && p.NameRoute == route.NameRoute).FirstOrDefaultAsync() != null)
            {
                ModelState.AddModelError("Дубликат", "Рейс на Этот день уже создан");
            }



            if (ModelState.IsValid)
            {
                db.Routes.Add(route);
                await db.SaveChangesAsync();
                return RedirectToAction("Index","Home");
            }

            return View(route);
        }*/

        // GET: Routes/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Route route = await db.Routes.FindAsync(id);
            if (route == null)
            {
                return HttpNotFound();
            }
            return View(route);
        }

        // POST: Routes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,NameDriver,NameRoute,RoadTypeRoute,DateRoute")] Route route)
        {
          



            if (ModelState.IsValid)
            {
                db.Entry(route).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index", "Home"); 
            }
            return View(route);
        }

        // GET: Routes/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Route route = await db.Routes.FindAsync(id);
            if (route == null)
            {
                return HttpNotFound();
            }
            return View(route);
        }

        // POST: Routes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Route route = await db.Routes.FindAsync(id);
            var clients = await db.Clients.Where(p=> p.RouteId == id).ToListAsync();
            foreach (var item in clients)
            {
                item.RouteId = null;
                db.Entry(item).State = EntityState.Modified;
                await db.SaveChangesAsync();
            }
            db.Routes.Remove(route);
            await db.SaveChangesAsync();
            return RedirectToAction("Index", "Home");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

busalert/Bus/Views/Moderator/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

busalert/Bus/Views/Moderator/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

busalert/Bus/Views/Moderator/CreatePar.cshtml
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">


        <div  class="form-group">
            <label class="control-label col-md-2" for="RoadType">RoadType</label>
            <div class="col-md-10">
                <div class="checkbox">
                    <input class="check-box" data-val="true" data-val-required="Требуется поле RoadType." id="RoadType" name="RoadType" type="checkbox" value="true" /><input name="RoadType" type="hidden" value="false" />
                    <span class="field-validation-valid text-danger" data-valmsg-for="RoadType" data-valmsg-replace="true"></span>
                </div>
            </div>
        </div>

        <div  class="form-group">
            <label class="control-label col-md-2" for="Date">Date</label>
            <div class="col-md-10">
                <input class="form-control text-box single-line" data-val="true" data-val-maxlength="Поле Date должно иметь тип строки или массива с максимальной длиной &quot;20&quot;." data-val-maxlength-max="20" data-val-required="Требуется поле Date." id="Date" name="Date" type="text" value="" />
                <span class="field-validation-valid text-danger" data-valmsg-for="Date" data-valmsg-replace="true"></span>
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2" for="FIO">FIO</label>
            <div class="col-md-10">
                <input class="form-control text-box single-line" data-val="true" data-val-required="Требуется поле FIO." id="FIO" name="FIO" type="text" value="" />
                <span class="field-validation-valid text-danger" data-valmsg-for="FIO" data-valmsg-replace="true"></span>
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2" for="Phone">Phone</label>
            <div class="col-md-10">
                <input class="form-control text-box single-line" data-val="true" data-val-required="Требуется поле Phone." id="Phone" name="Phone" type="text" value="" />
                <span class="field-validation-valid text-danger" data-valmsg-for="Phone" data-valmsg-replace="true"></span>
            </div>
        </div>

        <div  class="form-group">
            <label class="control-label col-md-2" for="Place">Place</label>
            <div class="col-md-10">
                <input class="form-control text-box single-line" data-val="true" data-val-maxlength="Поле Place должно иметь тип строки или массива с максимальной длиной &quot;20&quot;." data-val-maxlength-max="20" data-val-required="Требуется поле Place." id="Place" name="Place" type="text" value="" />
                <span class="field-validation-valid text-danger" data-valmsg-for="Place" data-valmsg-replace="true"></span>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>

}

busalert/Bus/Views/Moderator/LoadClients.cshtml
@model IEnumerable<Bus.Models.Client>

@if (Model.Count() == 0)
{
    <h3 id='roadHCl' class='h3 text-center'>Пассажиров Нет</h3>

    <button style="margin:50px 0 0 0;" id="addClientBut" data-toggle="modal" data-target="#basicModal" class="btn btn-default">Добавить Пассажира</button>

}

else
{


    <button style="margin:50px 0 0 0;" id="addClientBut" data-toggle="modal" data-target="#basicModal" class="btn btn-default">Добавить Пассажира</button>




            <table class="table">
                <tr>


                    <th>
                        @Html.DisplayNameFor(model => model.FIO)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Phone)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.PlaceBus)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Date)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.CoordsFrom)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.CoordsTo)
                    </th>
                    <th>
                        Пассажиры
                    </th>
                    <th></th>

                </tr>

                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.FIO)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Phone)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.PlaceBus)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Date)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.CoordsFrom)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.CoordsTo)
                        </td>
                        <td>
                            @if (item.RouteId == null)
                    {
                                @Html.Raw("Маршрут Не Присвоен")
                            }
                            else
                            {
                                @Html.Raw("Маршрут:" + item.Route.NameRoute + ",Водитель:" + item.Route.NameDriver)
                            }
                        </td>

                        <td>
                            @Html.ActionLink("Ред.", "Edit", "Clients", new { id = item.Id }, null) |

                            @Html.ActionLink("Удл.", "Delete", "Clients", new { id = item.Id }, null)
                        </td>
                    </tr>
                }

            </table>
}

busalert/Bus/Views/Moderator/LoadRoutes.cshtml
@model IEnumerable<Bus.Models.Route>

@if (Model.Count() == 0)
{
    <h3 id='roadHCl' class='h3 text-center'>Маршрутов Нет</h3>


    <button style="margin:50px 0 0 0;" id="AddRouteBut" class="btn btn-default">Добавить Маршрут</button>

}

else
{


    <button style="margin:50px 0 0 0;" id="AddRouteBut" class="btn btn-default">Добавить Маршрут</button>




    <table class="table">
        <tr>


            <th>
                @Html.DisplayNameFor(model => model.NameDriver)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NameRoute)
            </th>



            <th>
                Имена Пассажиров
            </th>

            <th>
                Откуда Забирать
            </th>

            <th>
                Куда Везти
            </th>

            <th>
                Количество Людей
            </th>

            <th></th>

        </tr>

        @foreach (var item in Model)
                {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.NameDriver)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NameRoute)
                </td>

                <td>
                    @{
                        var clients = "";
                        foreach (var client in item.Clients)
                        {
                            clients += client.FIO.ToString() + ", ";
                        }

                        if (clients == "")
                        {
                            clients = "Пасажиры Не Добавлены";
                        }
                        else
                        {

                            clients = clients.Substring(0, clients.Length - 2);
                        }
                    }

                    @clients
                </td>

                <td>
                    <a href='/maps?coordsType=false&id=@item.Id'>@ViewBag.url/maps?coordsType=false&id=@item.Id</a>

                </td>

                <td>
                    <a href='/maps?coordsType=true&id=@item.Id'>@ViewBag.url/maps?coordsType=true&id=@item.Id</a>

                </td>

                <td>
                    @item.Clients.Count()
                </td>


                <td>
                    @Html.ActionLink("Ред.", "Edit", "Routes", new { id = item.Id }, null) |

                    @Html.ActionLink("Удл.", "Delete", "Routes", new { id = item.Id }, null)
                </td>
            </tr>
                        }

    </table>
                        }


<script type="text/javascript">

    $(document).on("click", "#AddRouteBut", function () {
        debugger;
        $("#selectClients").html("@Html.Raw(ViewBag.FreeClients)");
        $('.selectpicker').selectpicker();
    });

    $(document).on("click", "#addClientBut", function () {
        debugger;
        $("#selectRoutes").html("@Html.Raw(ViewBag.SelectRoutes)");

    });

    



</script>